config/routes.rb
Rails.application.routes.draw do
  resources :gemini_configs, except: [:destroy] do 
    resources :gemini_config_parts, shallow: true
  end

  resources :conversations do 
    resources :conversation_contents, shallow: true
  end
  use_doorkeeper

  resources :packages do 
    resources :package_versions, shallow: true
  end
  
  resources :users

  devise_for :users, path: "auth", controllers: {
    registrations: "users/registrations",
  }
  
  resources :games do 
    resources :game_versions, shallow: true do 
      resources :game_version_package_versions, shallow: true
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "games#index"
end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id                   :bigint           not null, primary key
#  send_baseline_prompt :boolean          default(TRUE)
#  send_documentation   :boolean          default(TRUE)
#  send_project_code    :boolean          default(TRUE)
#  title                :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  user_id              :bigint           not null
#
# Indexes
#
#  index_conversations_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Conversation < ApplicationRecord
  belongs_to :user
  has_many :conversation_contents, dependent: :destroy

  broadcasts_refreshes

  def receive_message!
    content = conversation_contents.order(:created_at)

    new_content = content.last

    body =  {
      contents: content.map(&:for_request) 
    }

    Rails.logger.debug body

    response = user.gemini_client.generate_content(body)

    Rails.logger.debug response

    next_content = conversation_contents.create(
      role: "model",
      text: response["candidates"].first["content"]["parts"].first["text"],
      user:,
      token_count: response["usageMetadata"]["candidatesTokenCount"],
      prev: new_content
    )

    new_content.update(next: next_content)
  end

  def send_message(what)
    conversation_contents.build(
      role: "user",
      text: what,
      user:,
      prev: last_message
    )
  end

  def token_count 
    conversation_contents.sum(:token_count)
  end

  def last_message 
    conversation_contents.order(:created_at).last
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: %i[ show edit update destroy ]

  # GET /conversations or /conversations.json
  def index
    @conversations = policy_scope(Conversation.all.order(created_at: :desc))
  end

  # GET /conversations/1 or /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
    authorize @conversation
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.user = current_user

    authorize @conversation

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversation_url(@conversation), notice: "Conversation was successfully created." }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1 or /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to conversation_url(@conversation), notice: "Conversation was successfully updated." }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1 or /conversations/1.json
  def destroy
    @conversation.destroy!

    respond_to do |format|
      format.html { redirect_to conversations_url, notice: "Conversation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
      authorize @conversation
    end

    # Only allow a list of trusted parameters through.
    def conversation_params
      params.require(:conversation).permit(:title, :send_baseline_prompt, :send_documentation, :send_project_code)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= show_for conversation do %>
  <%= _1.attribute :title %>
  <%= _1.attribute :token_count %>
<% end %>

app/views/conversations/_form.html.erb
<%= simple_form_for conversation do %>
  <%= _1.input :title %>
  <%= _1.input :send_baseline_prompt %>
  <%= _1.input :send_documentation %>
  <%= _1.input :send_project_code %>
  <%= _1.button :submit %>
<% end %>

app/views/conversations/edit.html.erb
<section class="section">
  <div class="container">
    <%= render "shared/hero", title: "Editing conversation" %>
    <%= render "form", conversation: @conversation %>
  </div>
</section>

app/views/conversations/index.html.erb
<p style="color: green"><%= notice %></p>
<section class="section">
  <div class="container">
    <%= render "shared/hero", title: "Conversations" %>

    <div id="conversations">
      <% @conversations.each do |conversation| %>
        <div class="box">
          <%= render conversation %>
          <p>
            <%= link_to "Show this conversation", conversation %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/conversations/new.html.erb
<section class="section">
  <div class="container">
    <%= render 'shared/hero', title: "New Conversation" %>

    <%= render "form", conversation: @conversation %>

    <br>

    <div>
      <%= link_to "Back to conversations", conversations_path %>
    </div>
  </div>
</section>

app/views/conversations/show.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_stream_from @conversation %>
<section class="section">
  <div class="container">
    <%= render "shared/hero", title: "Conversation" %>
    <div class="box">
      <%= render @conversation %>
    </div>
    <%= turbo_frame_tag dom_id(@conversation, :contents), src: conversation_conversation_contents_path(@conversation), refresh: :morph do %>
      <p>Loading contents...</p>
    <% end %>
  </div>
</section>