config/routes.rb
Rails.application.routes.draw do
  resources :gemini_configs, except: [:destroy] do 
    resources :gemini_config_parts, shallow: true
  end

  resources :conversations do 
    resources :conversation_contents, shallow: true
  end
  use_doorkeeper

  resources :packages do 
    resources :package_versions, shallow: true
  end
  
  resources :users

  devise_for :users, path: "auth", controllers: {
    registrations: "users/registrations",
  }
  
  resources :games do 
    resources :game_versions, shallow: true do 
      resources :game_version_package_versions, shallow: true
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "games#index"
end

app/models/gemini_config.rb
# == Schema Information
#
# Table name: gemini_configs
#
#  id                  :bigint           not null, primary key
#  maximum_tokens      :integer
#  requests_per_day    :integer          default(1500)
#  requests_per_minute :integer          default(1000000)
#  tokens_per_minute   :integer          default(15)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class GeminiConfig < ApplicationRecord
    has_many :gemini_config_parts, dependent: :destroy

    has_one_attached :documentation

    after_commit :process_documentation, if: -> { attachment_changes["documentation"].present? }

    def self.instance 
        first_or_create
    end

    def process_documentation
        return unless documentation.attached?

        tempfile = Tempfile.new(binmode: true)
        tempfile.write(documentation.download)
        tempfile.close

        @documentation_contents = ["The following is the documentation for the UGC gaming platform"]

        Zip::File.open(tempfile.path) do |zip|
            zip.each do |entry|
                next unless entry.file?
                next if entry.name.include?("tutorial")


                @documentation_contents << 
                    <<~FILE
                        # #{entry.name}
                        
                        #{entry.get_input_stream.read}
                    FILE
            end
        end

        @documentation_contents
    end

    def documentation_contents
        process_documentation unless @documentation_contents
        @documentation_contents
    end
end

app/controllers/gemini_configs_controller.rb
class GeminiConfigsController < ApplicationController
  before_action :set_gemini_config, only: %i[ show edit update ]

  # GET /gemini_configs or /gemini_configs.json
  def index
    @gemini_configs = GeminiConfig.all

    authorize @gemini_configs
  end

  # GET /gemini_configs/1 or /gemini_configs/1.json
  def show
  end

  # GET /gemini_configs/new
  def new
    @gemini_config = GeminiConfig.new
    authorize @gemini_config
  end

  # GET /gemini_configs/1/edit
  def edit
  end

  # POST /gemini_configs or /gemini_configs.json
  def create
    @gemini_config = GeminiConfig.new(gemini_config_params)

    authorize @gemini_config

    respond_to do |format|
      if @gemini_config.save
        format.html { redirect_to gemini_config_url(@gemini_config), notice: "Gemini config was successfully created." }
        format.json { render :show, status: :created, location: @gemini_config }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gemini_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gemini_configs/1 or /gemini_configs/1.json
  def update
    respond_to do |format|
      if @gemini_config.update(gemini_config_params)
        format.html { redirect_to gemini_config_url(@gemini_config), notice: "Gemini config was successfully updated." }
        format.json { render :show, status: :ok, location: @gemini_config }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gemini_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gemini_configs/1 or /gemini_configs/1.json
  # def destroy
  #   @gemini_config.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to gemini_configs_url, notice: "Gemini config was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gemini_config
      @gemini_config = GeminiConfig.find(params[:id])
      authorize @gemini_config
    end

    # Only allow a list of trusted parameters through.
    def gemini_config_params
      params.require(:gemini_config).permit(:tokens_per_minute, :requests_per_minute, :requests_per_day, :documentation)
    end
end

app/helpers/gemini_configs_helper.rb
module GeminiConfigsHelper
end

app/views/gemini_configs/_form.html.erb
<%= simple_form_for gemini_config do %>
  <%= _1.input :tokens_per_minute %>
  <%= _1.input :requests_per_day %>
  <%= _1.input :requests_per_minute %>
  <%= _1.input :documentation %>
  <%= _1.button :submit %>
<% end %>

app/views/gemini_configs/_gemini_config.html.erb
<%= show_for gemini_config do %>
    <%= _1.attribute :tokens_per_minute %>
    <%= _1.attribute :requests_per_minute %>
    <%= _1.attribute :requests_per_day %>
<% end %>

app/views/gemini_configs/edit.html.erb
<section class="section">
  <div class="container">
    <%= render "shared/hero", title: "Editing gemini config" %>
    <%= render "form", gemini_config: @gemini_config %>
  </div>
</section>

app/views/gemini_configs/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Gemini configs</h1>
<div id="gemini_configs">
  <% @gemini_configs.each do |gemini_config| %>
    <div class="box">
      <%= render gemini_config %>
      <p>
        <%= link_to "Show this gemini config", gemini_config %>
      </p>
    </div>
  <% end %>
</div>
<%= link_to "New gemini config", new_gemini_config_path %>

app/views/gemini_configs/new.html.erb
<h1>New gemini config</h1>

<%= render "form", gemini_config: @gemini_config %>

<br>

<div>
  <%= link_to "Back to gemini configs", gemini_configs_path %>
</div>

app/views/gemini_configs/show.html.erb
<p style="color: green"><%= notice %></p>
<section class="section">
  <div class="container">
    <%= render "shared/hero", title: "Gemini Config", exclude: [:index] %>

    <div class="box">
      <%= render @gemini_config %>
    </div>
    <%= turbo_frame_tag dom_id(@gemini_config, :parts), src: gemini_config_gemini_config_parts_url(@gemini_config), refresh: :morph do %>
      <p>Loading contents...</p>
    <% end %>
  </div>
</section>