config/routes.rb
Rails.application.routes.draw do
  resources :gemini_configs, except: [:destroy] do 
    resources :gemini_config_parts, shallow: true
  end

  resources :conversations do 
    resources :conversation_contents, shallow: true
  end
  use_doorkeeper

  resources :packages do 
    resources :package_versions, shallow: true
  end
  
  resources :users

  devise_for :users, path: "auth", controllers: {
    registrations: "users/registrations",
  }
  
  resources :games do 
    resources :game_versions, shallow: true do 
      resources :game_version_package_versions, shallow: true
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "games#index"
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id                               :bigint           not null, primary key
#  description                      :text
#  name                             :string
#  created_at                       :datetime         not null
#  updated_at                       :datetime         not null
#  latest_game_version_id           :bigint
#  latest_published_game_version_id :bigint
#  user_id                          :bigint           not null
#
# Indexes
#
#  index_games_on_latest_game_version_id            (latest_game_version_id)
#  index_games_on_latest_published_game_version_id  (latest_published_game_version_id)
#  index_games_on_user_id                           (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (latest_game_version_id => game_versions.id)
#  fk_rails_...  (latest_published_game_version_id => game_versions.id)
#  fk_rails_...  (user_id => users.id)
#
class Game < ApplicationRecord
  belongs_to :user
  has_many :game_versions, dependent: :destroy
  belongs_to :latest_game_version, class_name: "GameVersion", required: false
  belongs_to :latest_published_game_version, class_name: "GameVersion", required: false

  has_one_attached :cover_image

  before_save :assign_latest

  def assign_latest
    self.latest_game_version = game_versions.order(created_at: :desc).first
    self.latest_published_game_version = game_versions.published.order(created_at: :desc).first
  end

  def assign_latest!
    assign_latest
    save
  end

  # def latest_game_version
  #     game_versions.order(created_at: :desc).first
  # end

  # def latest_published_game_version
  #     game_versions.published.order(created_at: :desc).first
  # end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
    authorize @game
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)
    @game.user = current_user

    authorize @game

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy!

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
      authorize @game
    end

    # Only allow a list of trusted parameters through.
    def game_params
      Rails.logger.info params
      params.require(:game).permit(:name, :description, :cover_image)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for game do %>
  <%= _1.input :name %>
  <%= _1.input :description %>
  <%= _1.input :cover_image %>
  <%= _1.button :submit %>
<% end %>

app/views/games/_game.html.erb
<%= show_for game do |g| %>
  <%= g.attribute :cover_image do %>
    <%= image_tag(game.cover_image, class: "max-w-40") if game.cover_image.attached? %>
  <% end %>
  <%= g.attribute :name %>
  <%= g.attribute :description %>
<% end %>

app/views/games/edit.html.erb
<section class="section">
  <div class="container">
    <%= render "shared/hero", title: "Editing game" %>
    <%= render "form", game: @game %>
  </div>
</section>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>
<section class="section">
  <div class="container" id="games">
    <%= render "shared/hero", title: "Games" %>
    <% @games.each do |game| %>
      <div class="box">
        <%= render game %>
        <p>
          <%= link_to "Show this game", game %>
        </p>
      </div>
    <% end %>
  </div>
</section>

app/views/games/new.html.erb
<section class="section">
  <div class="container">
    <%= render "shared/hero", title: "New Game", link: games_path, link_text: "Back to games" %>
    <%= render "form", game: @game %>
  </div>
</section>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>
<section class="section">
  <div class="container">
    <%= render "shared/hero", title: @game.name, link: games_path, link_text: "Back to games" %>
    <div class="box">
      <%= render @game %>
    </div>
    <%= turbo_frame_tag dom_id(@game, :versions), src: game_game_versions_path(@game) do %>
      <p>Loading versions...</p>
    <% end %>
  </div>
</section>