config/routes.rb
Rails.application.routes.draw do
  resources :gemini_configs, except: [:destroy] do 
    resources :gemini_config_parts, shallow: true
  end

  resources :conversations do 
    resources :conversation_contents, shallow: true
  end
  use_doorkeeper

  resources :packages do 
    resources :package_versions, shallow: true
  end
  
  resources :users

  devise_for :users, path: "auth", controllers: {
    registrations: "users/registrations",
  }
  
  resources :games do 
    resources :game_versions, shallow: true do 
      resources :game_version_package_versions, shallow: true
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "games#index"
end

app/views/layouts/_navbar.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M4 6h16M4 12h8m-8 6h16" />
        </svg>
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow"
      >
        <% if current_user %>
          <li>
            <%= link_to games_url, class: "navbar-item" do %>
              Games
            <% end %>
          </li>

          <li>
            <%= link_to packages_url, class: "navbar-item" do %>
              Packages
            <% end %>
          </li>

          <li>
            <%= link_to conversations_url, class: "navbar-item" do %>
              Conversations
            <% end %>
          </li>

          <%- if current_user && current_user.admin? %>
            <li>
              <%= link_to gemini_config_url(GeminiConfig.instance), class: "navbar-item" do %>
                Gemini Config
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <a class="btn btn-ghost text-xl">Koinonia</a>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      <% if current_user %>
          <li>
            <%= link_to games_url, class: "navbar-item" do %>
              Games
            <% end %>
          </li>

          <li>
            <%= link_to packages_url, class: "navbar-item" do %>
              Packages
            <% end %>
          </li>

          <li>
            <%= link_to conversations_url, class: "navbar-item" do %>
              Conversations
            <% end %>
          </li>

          <%- if current_user && current_user.admin? %>
            <li>
              <%= link_to gemini_config_url(GeminiConfig.instance), class: "navbar-item" do %>
                Gemini Config
              <% end %>
            </li>
          <% end %>
        <% end %>
    </ul>
  </div>
  <div class="navbar-end">
    <ul class="menu menu-horizontal px-1">
      <% if current_user %>
        <li class="justify-center"><%= link_to "Profile", user_url(current_user), class: "navbar-item" %></li>
        <li class="justify-center">
          <%= button_to destroy_user_session_url, class: "navbar-item", method: :delete do %>
            Log out
          <% end %>
        </li>
        
      <% else %>
        <li class="justify-center">
          <%= link_to new_user_registration_url, class: "navbar-item" do %>
            <strong>Sign up</strong>
          <% end %>
        </li>

        <li class="justify-center">
          <%= link_to new_user_session_url, class: "navbar-item" do %>
            Log in
          <% end %>
        </li>

      <% end %>
      <li>
        <div class="dropdown">
          <div tabindex="0" role="button" class="btn m-1">
            Theme
            <svg
              width="12px"
              height="12px"
              class="inline-block h-2 w-2 fill-current opacity-60"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 2048 2048">
              <path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path>
            </svg>
          </div>
          <ul tabindex="0" class="dropdown-content bg-base-300 rounded-box z-[1] w-52 p-2 shadow-2xl max-h-96 overflow-y-scroll top-0 right-0" data-controller="theme-change">
            <% themes.each do |theme| %>
              <li>
                <input
                  type="radio"
                  name="theme-dropdown"
                  class="btn btn-sm btn-block btn-ghost justify-start"
                  aria-label="<%= theme %>"
                  data-set-theme="<%= theme %>"
                  value="<%= theme %>" />
              </li>
            <% end %>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotCraytaWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve  %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
  </head>
  <body>
    <%= render "layouts/navbar", current_user: current_user %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>